apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: KafkaNodePool
    patch: |-
      - op: replace
        path: /spec/template/pod/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "strimzi.io/cluster"
                      operator: In
                      values:
                        - "my-cluster"
