apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../gitops/operators/grafana-operator

components:
  - ../../../../gitops/instance/grafana/strimzi
#   - ../../gitops/instance/prometheus/strimzi

patches:
  - target:
      kind: OperatorGroup
      name: grafana-operator
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value:
          - strimzi-metrics
#   - target:
#       kind: OperatorGroup
#       name: prometheus
#     patch: |-
#       - op: replace
#         path: /spec/targetNamespaces
#         value:
#           - strimzi-metrics
