apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: demo.topic01
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
  config:
    retention.ms: 300000
    segment.bytes: 1073741824
