apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: KafkaNodePool
      name: controller
    patch: |-
      - op: replace
        path: /spec/template/pod/topologySpreadConstraints
        value:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                strimzi.io/pool-name: "controller"
  - target:
      kind: KafkaNodePool
      name: broker
    patch: |-
      - op: replace
        path: /spec/template/pod/topologySpreadConstraints
        value:
          - topologyKey: "topology.kubernetes.io/zone"
            maxSkew: 1
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                strimzi.io/pool-name: "broker"
