apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

components:
  - ../../../gitops/instance/kafka/components/consumer
  - ../../../gitops/instance/kafka/components/producer
  - ../../../gitops/instance/kafka/components/topic
  - ../../../gitops/instance/kafka/components/tls

patches:
  - target:
      kind: Deployment
      name: kafka-consumer-perf-test
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "registry.redhat.io/amq-streams/kafka-40-rhel9:3.0.1"
  - target:
      kind: Deployment
      name: kafka-producer-perf-test
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "registry.redhat.io/amq-streams/kafka-40-rhel9:3.0.1"
