apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../gitops/instance/kafka/components/consumer
  - ../../../../gitops/instance/kafka/components/producer
  - ../../../../gitops/instance/kafka/components/topic
