apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafana-streams-datasource
  namespace: streams-metrics
spec:
  instanceSelector:
    matchLabels:
      dashboards: "streams"
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated:9090
    isDefault: true
    jsonData:
      "timeInterval": "5s"
    editable: true
