---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: mm-user
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls: []
