apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana
  - namespace.yaml
  # - prometheus

patches:
  - target:
      kind: OperatorGroup
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value:
          - strimzi-metrics
