apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - includeSelectors: true
    pairs:
      app: kafka

resources:
  - users.yaml

patches:
  - target:
      kind: Kafka
    patch: |-
      - op: add
        path: /spec/kafka/authorization/type
        value: simple
      - op: add
        path: /spec/kafka/listeners
        value:
          - name: tls
            port: 9093
            type: internal
            tls: true
            authentication:
              type: tls
          - name: external
            port: 9094
            type: route
            tls: true
            authentication:
              type: tls
