apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: client-user
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "demo.topic01"
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
        host: "*"
      - resource:
          type: group
          name: client-group
          patternType: literal
        operations:
          - Read
        host: "*"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: mm-user
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls: []
