kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-producer-perf-test
data:
  bootstrap-server: "my-cluster-kafka-bootstrap:9092"
  num-records: "9223372036854775807"
  topic: "demo.topic01"
  throughput: "-1"
  record-size: "64000"
  kafka-producer.properties: |
    batch.size=16384
    compression.type=snappy
