apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - base
  - grafana-operator

patches:
  - target:
      kind: OperatorGroup
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value:
          - kafka-metrics
