---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: mm-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls: []
