apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-perf-test
  labels:
    app: kafka-consumer-perf-test
spec:
  selector:
    matchLabels:
      app: kafka-consumer-perf-test
  replicas: 0
  template:
    metadata:
      labels:
        app: kafka-consumer-perf-test
    spec:
      containers:
        - name: "kafka-consumer-perf-test"
          image: "registry.redhat.io/amq-streams/kafka-38-rhel9:2.8.0"
          env:
            - name: "KAFKA_CONSUMER_PERF_TEST_TOPIC"
              valueFrom:
                configMapKeyRef:
                  name: "kafka-consumer-perf-test-configmap"
                  key: "topic"
            - name: "KAFKA_CONSUMER_PERF_TEST_MESSAGES"
              valueFrom:
                configMapKeyRef:
                  name: "kafka-consumer-perf-test-configmap"
                  key: "messages"
            - name: "KAFKA_CONSUMER_PERF_TEST_BOOTSTRAP_SERVER"
              valueFrom:
                configMapKeyRef:
                  name: "kafka-consumer-perf-test-configmap"
                  key: "bootstrap-server"
          command:
            - "/opt/kafka/bin/kafka-consumer-perf-test.sh"
          args:
            - "--consumer.config"
            - "/etc/config/kafka-consumer.properties"
            - "--messages"
            - "$(KAFKA_CONSUMER_PERF_TEST_MESSAGES)"
            - "--topic"
            - "$(KAFKA_CONSUMER_PERF_TEST_TOPIC)"
            - "--bootstrap-server"
            - "$(KAFKA_CONSUMER_PERF_TEST_BOOTSTRAP_SERVER)"
            - "--print-metrics"
          volumeMounts:
            - name: "kafka-consumer-perf-test-configmap-vol"
              mountPath: "/etc/config"
              readOnly: true
      volumes:
        - name: "kafka-consumer-perf-test-configmap-vol"
          configMap:
            name: "kafka-consumer-perf-test-configmap"
            items:
              - key: "kafka-consumer.properties"
                path: "kafka-consumer.properties"
