kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-consumer-perf-test-configmap
  labels:
    app: strimzi
data:
  topic: "demo.topic01"
  messages: "9223372036854775807"
  bootstrap-server: "my-cluster-kafka-bootstrap.streams:9092"
  kafka-consumer.properties: |
    compression.type=snappy
    fetch.max.bytes=52428800
    fetch.min.bytes=1048576
    group.id=kafka-consumer-perf-test
    group.protocol=classic
