apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: streams

resources:
  - ../base

patches:
  - target:
      kind: ConfigMap
      name: kafka-consumer-perf-test-configmap
    patch: |-
      - op: replace
        path: /data/bootstrap-server
        value: "my-cluster-kafka-bootstrap.streams:9093"
  - target:
      kind: Deployment
      name: kafka-consumer-perf-test
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "registry.redhat.io/amq-streams/kafka-40-rhel9:3.0.1"
  - target:
      kind: ConfigMap
      name: kafka-producer-perf-test-configmap
    patch: |-
      - op: replace
        path: /data/bootstrap-servers
        value: "my-cluster-kafka-bootstrap.streams:9093"
  - target:
      kind: Deployment
      name: kafka-producer-perf-test
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "registry.redhat.io/amq-streams/kafka-40-rhel9:3.0.1"
  - target:
      kind: KafkaTopic
      name: demo.topic01
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
